### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by kpym** [remykarem/python2jupyter#6] opened 2019-12-08 11:43 UTC
There is an encoding problem.
This UTF8 encoded source file:
```python
# Les deux courbes sont très proches
```
produce the markdown cell
```
Les deux courbes sont trÃ¨s proches
```
And the resulting `.ipynb` is in UTF8 ... but somewhere the encoding was messed up.

**Comment by remykarem** [comment] 2020-05-11 15:35
Hi, I'm unable to reproduce this bug. Could you share with me this source file?

**Comment by kpym** [comment] 2020-05-11 15:56
Strange that you can't reproduce it. I just transformed my comment to single line utf8 python file 
```py
# Les deux courbes sont très proches
```
and after converting it with `p2j` I obtain:
```json
{"cells": [{"cell_type": "markdown", "metadata": {}, "source": ["Les deux courbes sont tr\u00c3\u00a8s proches"]}], "metadata": {"kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"}, "language_info": {"codemirror_mode": {"name": "ipython", "version": 3}, "file_extension": ".py", "mimetype": "text/x-python", "name": "python", "nbconvert_exporter": "python", "pygments_lexer": "ipython3", "version": "3.6.4"}}, "nbformat": 4, "nbformat_minor": 2}
```
where you can see that `très` is converted to `tr\u00c3\u00a8s`.

**Comment by remykarem** [comment] 2020-05-13 09:50
Could you please attach the file on this page so that I can try it?

**Comment by kpym** [comment] 2020-05-13 13:20
The content of my files is already in my previous comment. But ok, here is the one line `.py` file available on [ghostbin](https://ghostbin.co/paste/znu9q).

**Comment by remykarem** [comment] 2020-05-20 12:59
I still can't reproduce the error. What version of Python are you on? And what version of `p2j`?

**Comment by kpym** [comment] 2020-05-20 13:38
I'm using Windows 10, with Python 3.7.7. Knowing the version of `p2j` is not easy, there is no `-v` flag and `-h` flag do not print the version.

First, I installed the last version with `pip install p2j` : the behaviour with the produced `p2j.exe` is what I described.

Second, I cloned your repo and run `python p2j.py test.py`. Same result with `\u00c3\u00a8` in place of `è`.

Probably you use somewhere the system encoding, and probably it is not the same in Windows and in your OS.

**Comment by remykarem** [comment] 2020-05-20 13:55
I see. Could you print out the following in a Python interpreter?

```python
import sys
sys.getdefaultencoding()
```

and

```python
print("è".encode("utf-8").decode())
```

**Comment by kpym** [comment] 2020-05-20 16:39
The answer is (in `GitBash` and in `PowerShell`) : 

```bash
utf-8
è
```
I change the default encoding in my terminals to `utf-8`.

**Comment by remykarem** [comment] 2020-06-01 14:12
I'm unable to find a solution to this bug. We'll leave it open for now. In the meantime, if you find a fix, do submit a PR.

**Comment by kpym** [comment] 2020-06-01 14:36
Thanks for considering this. If I have time, I'll take a look at it.

**Comment by ktzanev** [comment] 2020-06-22 07:43
I've checked. You should open the source `.py` as utf-8 on [line 32](https://github.com/remykarem/python2jupyter/blob/e63f1658cbc2f82482bd59e3f34d43c02dee980d/p2j/p2j.py#L32)
```py
with open(source_filename, 'r', encoding='utf-8') as infile:
```
And you should dump the json as utf-8 on lines [161-162](https://github.com/remykarem/python2jupyter/blob/e63f1658cbc2f82482bd59e3f34d43c02dee980d/p2j/p2j.py#L161-L162) :
```py
with open(target_filename, 'w', encoding='utf-8') as outfile:
    json.dump(final, outfile, indent=1, ensure_ascii=False)
```

The default encoding is [platform dependent](https://stackoverflow.com/a/36316351), this is why it was working on some systems and not on others.
It is always a good practice to open text files with specified encoding.

**Comment by remykarem** [comment] 2020-07-04 11:37
Hi @ktzanev that's a good point! @kpym I've merged these changes into master. Can you try again and see if the problem persists?

**Comment by kpym** [comment] 2020-07-04 11:42
**EDIT: I made a previous comment with a bad account, so I put it back here for historical reasons.**

I've checked. You should open the source `.py` as utf-8 on [line 32](https://github.com/remykarem/python2jupyter/blob/e63f1658cbc2f82482bd59e3f34d43c02dee980d/p2j/p2j.py#L32)
```py
with open(source_filename, 'r', encoding='utf-8') as infile:
```
And you should dump the json as utf-8 on lines [161-162](https://github.com/remykarem/python2jupyter/blob/e63f1658cbc2f82482bd59e3f34d43c02dee980d/p2j/p2j.py#L161-L162) :
```py
with open(target_filename, 'w', encoding='utf-8') as outfile:
    json.dump(final, outfile, indent=1, ensure_ascii=False)
```

The default encoding is [platform dependent](https://stackoverflow.com/a/36316351), this is why it was working on some systems and not on others.
It is always a good practice to open text files with specified encoding.

**Comment by remykarem** [comment] 2020-07-04 11:45
Great :) Closing this issue.

**Closed by remykarem** 2020-07-04 11:45 UTC
Labels: bug
